<?php

    /*
        --------------------------
        Application bootstrapper
        Do not edit this file!
        --------------------------
    */

    // Load the settings
    define('APP_CONFIG', require_once('config.php'));

    // Load the bootstrapper
    require_once('src/bootstrapper.php');

    // Unleash ButterDocs!
    $app = new ButterDocs();
    $app->unleash();

?>