<html>

<head>
    <title><?= $title; ?></title>
    <base href="<?= $base_url; ?>">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="assets/images/favicon.png">

    <!-- CSS plugins -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/css/bootstrap.min.css">

    <!-- ButterDocs CSS -->
    <link rel="stylesheet" href="assets/css/themes/<?= $theme; ?>.css">
    <link rel="stylesheet" href="assets/css/butterdocs.css">
</head>

<body>
    <section class="not-found">
        <section class="inner">
            <h1>404</h1>
            <h3>Page not found!</h3>
            <a href="">
                <i class="fas fa-chevron-left"></i>
                Back to docs
            </a>
        </section>
    </section>
</body>

</html>