<html>

<head>
    <title><?= $title; ?></title>
    <base href="<?= $base_url; ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/themes/<?= $theme; ?>.css">
    <link rel="stylesheet" href="assets/css/butterdocs.css">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, user-scalable=no">
</head>

<body>
    <section class="layout">
        <section class="header">
            <a onclick="toggleSidenav();"><i class="fas fa-bars"></i></a>
            <?= $application; ?>
        </section>
        <section class="menu">
            <a href="<?= $version; ?>">
                <img src="assets/images/logo.png" class="logo">
            </a>
            <div class="dropdown">
                <a class="dropdown-toggle" data-bs-toggle="dropdown">
                    <?= $version; ?>
                </a>
                <ul class="dropdown-menu">
                    <?php foreach ($version_list as $v) : ?>
                        <li><a href="<?= $v; ?>" class="dropdown-item" href="#"><?= $v; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?= $menu; ?>
        </section>
        <section class="content">
            <?= $content; ?>
            <section class="copyright">
                <hr>
                Unleashed by ButterDocs
            </section>
        </section>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <script src="assets/js/butterdocs.js"></script>
</body>

</html>